/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as StudentsStudentIdAssessRouteImport } from './routes/students.$studentId.assess'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdAssessRoute = StudentsStudentIdAssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => StudentsStudentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/$studentId/assess': typeof StudentsStudentIdAssessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/$studentId/assess': typeof StudentsStudentIdAssessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/$studentId/assess': typeof StudentsStudentIdAssessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/students/$studentId'
    | '/students/$studentId/assess'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/students/$studentId'
    | '/students/$studentId/assess'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/students/$studentId'
    | '/students/$studentId/assess'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId/assess': {
      id: '/students/$studentId/assess'
      path: '/assess'
      fullPath: '/students/$studentId/assess'
      preLoaderRoute: typeof StudentsStudentIdAssessRouteImport
      parentRoute: typeof StudentsStudentIdRoute
    }
  }
}

interface StudentsStudentIdRouteChildren {
  StudentsStudentIdAssessRoute: typeof StudentsStudentIdAssessRoute
}

const StudentsStudentIdRouteChildren: StudentsStudentIdRouteChildren = {
  StudentsStudentIdAssessRoute: StudentsStudentIdAssessRoute,
}

const StudentsStudentIdRouteWithChildren =
  StudentsStudentIdRoute._addFileChildren(StudentsStudentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  StudentsStudentIdRoute: StudentsStudentIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
